spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: orchestrator-sign-up
              uri: http://localhost:8989
              predicates:
                - Path=
                        # Sign-Up
                        /api/v*/auth/sign-up,
                        /api/v*/auth/oauth2/**
              filters:
                - StripPrefix=0

            - id: auth-service
              uri: http://localhost:8082
              predicates:
                  - Path=/api/v*/auth/**
              filters:
                  - StripPrefix=0